version: "3.3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.3.4
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.file.filename=/config.toml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=ERROR
    ports:
      - "80:80"
      - "8080:8080"  # The Web UI (enabled by --api.dashboard=true)
      - "443:443"
    networks:
      - admin
      - backend
      - php
      - frontend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config.toml:/config.toml"
      - "./certs:/certs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: always
    networks:
      - admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.service=frontendService"
      - "traefik.http.services.frontendService.loadbalancer.server.port=9000"

  whoami: # Testing container
    image: traefik/whoami
    hostname: whoami.localhost
    container_name: whoami
    restart: always
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

volumes:
  portainer_data:
    name: portainer_data

networks:
  admin:
    name: admin
  frontend:
    name: frontend
  backend:
    name: backend
  php:
    name: webserver
